FROM ubuntu:14.04
MAINTAINER Andrey Ustyuzhanin <anaderi@yandex-team.ru>

WORKDIR /root
ADD ./install-conda-env.sh /root/
ADD ./environment_py2.yaml /root/
#ADD ./environment_py3.yaml /root/
RUN /root/install-conda-env.sh

CMD ["bash"]
