FROM ubuntu:14.04
MAINTAINER Andrey Ustyuzhanin <anaderi@yandex-team.ru>

WORKDIR /root
ADD ./* /root/

RUN /root/install-conda-env.sh
RUN echo " \n\
  export PATH=$HOME/miniconda/bin:\$PATH \n\
  source activate rep_py2 \n\
  pushd \$ENV_BIN_DIR/.. ; source 'bin/thisroot.sh' ; popd \n\
" >> $HOME/.bashrc

CMD ["bash"]